workflows:
  bootstrap_signing:
    name: Bootstrap signing (create iOS Distribution p12 once)
    max_build_duration: 10
    environment:
      xcode: 16.4
      groups:
        - appstore_connect   # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        CERT_PASSWORD: "set-strong-password-here"   # после прогонa перенеси в Secrets
    scripts:
      - name: Generate PKCS#8 private key
        script: |
          set -euo pipefail
          # PKCS#1 -> PKCS#8 (нужен формат с заголовком BEGIN PRIVATE KEY)
          openssl genrsa -out dist_pkcs1.key 2048
          openssl pkcs8 -topk8 -in dist_pkcs1.key -nocrypt -out dist.key

      - name: Create iOS Distribution cert and package into p12
        script: |
          set -euo pipefail
          app-store-connect certificates create \
            --type IOS_DISTRIBUTION \
            --certificate-key "$(cat dist.key)" \
            --p12-password "$CERT_PASSWORD" \
            --p12-path dist.p12 \
            --save

      - name: Prepare artifact for Secrets (base64)
        script: |
          set -euo pipefail
          base64 < dist.p12 > dist.p12.b64
    artifacts:
      - dist.p12.b64
